package pojos;
// Generated 18-may-2020 21:40:24 by Hibernate Tools 4.3.1



/**
 * Anuncio generated by hbm2java
 */
public class Anuncio  implements java.io.Serializable {


     private String link;
     private Tema tema;
     private String titulo;
     private String imagen;

    public Anuncio() {
    }

    public Anuncio(String link, Tema tema, String titulo, String imagen) {
       this.link = link;
       this.tema = tema;
       this.titulo = titulo;
       this.imagen = imagen;
    }
   
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public Tema getTema() {
        return this.tema;
    }
    
    public void setTema(Tema tema) {
        this.tema = tema;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }




}


