package pojos;
// Generated 01-may-2020 13:21:32 by Hibernate Tools 4.3.1



/**
 * Anuncio generated by hbm2java
 */
public class Anuncio  implements java.io.Serializable {


     private String link;
     private Tema tema;
     private String titulo;

    public Anuncio() {
    }

    public Anuncio(String link, Tema tema, String titulo) {
       this.link = link;
       this.tema = tema;
       this.titulo = titulo;
    }
   
    public String getLink() {
        return this.link;   
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public Tema getTema() {
        return this.tema;
    }
    
    public void setTema(Tema tema) {
        this.tema = tema;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }




}


