package pojos;
// Generated 18-may-2020 21:40:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carpeta generated by hbm2java
 */
public class Carpeta  implements java.io.Serializable {


     private Integer idCarpeta;
     private String nombreCarpeta;
     private Usuario usuario;
     private Set guardadasEns = new HashSet(0);

    public Carpeta() {
    }

	
    public Carpeta(String nombreCarpeta, Usuario usuario) {
        this.nombreCarpeta = nombreCarpeta;
        this.usuario = usuario;
    }
    public Carpeta(String nombreCarpeta, Usuario usuario, Set guardadasEns) {
       this.nombreCarpeta = nombreCarpeta;
       this.usuario = usuario;
       this.guardadasEns = guardadasEns;
    }
   
    public String getNombreCarpeta() {
        return this.nombreCarpeta;
    }
    
    public void setNombreCarpeta(String nombreCarpeta) {
        this.nombreCarpeta = nombreCarpeta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Set getGuardadasEns() {
        return this.guardadasEns;
    }
    
    public void setGuardadasEns(Set guardadasEns) {
        this.guardadasEns = guardadasEns;
    }

    public Integer getIdCarpeta() {
        return idCarpeta;
    }

    public void setIdCarpeta(Integer idCarpeta) {
        this.idCarpeta = idCarpeta;
    }

    
    



}


