package pojos;
// Generated 19-may-2020 20:01:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carpeta generated by hbm2java
 */
public class Carpeta  implements java.io.Serializable {


     private Integer idCarpeta;
     private Usuario usuario;
     private String nombreCarpeta;
     private Set guardadasEns = new HashSet(0);

    public Carpeta() {
    }

	
    public Carpeta(String nombreCarpeta, Usuario usuario) {
        this.usuario = usuario;
        this.nombreCarpeta = nombreCarpeta;
    }
    public Carpeta(Usuario usuario, String nombreCarpeta, Set guardadasEns) {
       this.usuario = usuario;
       this.nombreCarpeta = nombreCarpeta;
       this.guardadasEns = guardadasEns;
    }
   
    public Integer getIdCarpeta() {
        return this.idCarpeta;
    }
    
    public void setIdCarpeta(Integer idCarpeta) {
        this.idCarpeta = idCarpeta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombreCarpeta() {
        return this.nombreCarpeta;
    }
    
    public void setNombreCarpeta(String nombreCarpeta) {
        this.nombreCarpeta = nombreCarpeta;
    }
    public Set getGuardadasEns() {
        return this.guardadasEns;
    }
    
    public void setGuardadasEns(Set guardadasEns) {
        this.guardadasEns = guardadasEns;
    }




}


