package pojos;
// Generated 01-may-2020 13:21:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carpeta generated by hbm2java
 */
public class Carpeta  implements java.io.Serializable {


     private int nombreCarpeta;
     private Usuario usuario;
     private Set guardadasEns = new HashSet(0);

    public Carpeta() {
    }

	
    public Carpeta(int nombreCarpeta, Usuario usuario) {
        this.nombreCarpeta = nombreCarpeta;
        this.usuario = usuario;
    }
    public Carpeta(int nombreCarpeta, Usuario usuario, Set guardadasEns) {
       this.nombreCarpeta = nombreCarpeta;
       this.usuario = usuario;
       this.guardadasEns = guardadasEns;
    }
   
    public int getNombreCarpeta() {
        return this.nombreCarpeta;
    }
    
    public void setNombreCarpeta(int nombreCarpeta) {
        this.nombreCarpeta = nombreCarpeta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Set getGuardadasEns() {
        return this.guardadasEns;
    }
    
    public void setGuardadasEns(Set guardadasEns) {
        this.guardadasEns = guardadasEns;
    }




}


