package pojos;
// Generated 19-may-2020 19:11:18 by Hibernate Tools 4.3.1



/**
 * GuardadasEnId generated by hbm2java
 */
public class GuardadasEnId  implements java.io.Serializable {


     private int idNoticia;
     private int idCarpeta;

    public GuardadasEnId() {
    }

    public GuardadasEnId(int idNoticia, int idCarpeta) {
       this.idNoticia = idNoticia;
       this.idCarpeta = idCarpeta;
    }
   
    public int getIdNoticia() {
        return this.idNoticia;
    }
    
    public void setIdNoticia(int idNoticia) {
        this.idNoticia = idNoticia;
    }
    public int getIdCarpeta() {
        return this.idCarpeta;
    }
    
    public void setIdCarpeta(int idCarpeta) {
        this.idCarpeta = idCarpeta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GuardadasEnId) ) return false;
		 GuardadasEnId castOther = ( GuardadasEnId ) other; 
         
		 return (this.getIdNoticia()==castOther.getIdNoticia())
 && (this.getIdCarpeta()==castOther.getIdCarpeta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdNoticia();
         result = 37 * result + this.getIdCarpeta();
         return result;
   }   


}


