package pojos;
// Generated 18-may-2020 21:40:24 by Hibernate Tools 4.3.1



/**
 * GuardadasEnId generated by hbm2java
 */
public class GuardadasEnId  implements java.io.Serializable {


     private int idNoticia;
     private String nombreCarpeta;

    public GuardadasEnId() {
    }

    public GuardadasEnId(int idNoticia, String nombreCarpeta) {
       this.idNoticia = idNoticia;
       this.nombreCarpeta = nombreCarpeta;
    }
   
    public int getIdNoticia() {
        return this.idNoticia;
    }
    
    public void setIdNoticia(int idNoticia) {
        this.idNoticia = idNoticia;
    }
    public String getNombreCarpeta() {
        return this.nombreCarpeta;
    }
    
    public void setNombreCarpeta(String nombreCarpeta) {
        this.nombreCarpeta = nombreCarpeta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GuardadasEnId) ) return false;
		 GuardadasEnId castOther = ( GuardadasEnId ) other; 
         
		 return (this.getIdNoticia()==castOther.getIdNoticia())
 && ( (this.getNombreCarpeta()==castOther.getNombreCarpeta()) || ( this.getNombreCarpeta()!=null && castOther.getNombreCarpeta()!=null && this.getNombreCarpeta().equals(castOther.getNombreCarpeta()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdNoticia();
         result = 37 * result + ( getNombreCarpeta() == null ? 0 : this.getNombreCarpeta().hashCode() );
         return result;
   }   


}


