package pojos;
// Generated 19-may-2020 20:01:26 by Hibernate Tools 4.3.1



/**
 * Voto generated by hbm2java
 */
public class Voto  implements java.io.Serializable {


     private Integer idVoto;
     private Noticia noticia;
     private Usuario usuario;
     private int valor;

    public Voto() {
    }

    public Voto(Noticia noticia, Usuario usuario, int valor) {
       this.noticia = noticia;
       this.usuario = usuario;
       this.valor = valor;
    }
   
    public Integer getIdVoto() {
        return this.idVoto;
    }
    
    public void setIdVoto(Integer idVoto) {
        this.idVoto = idVoto;
    }
    public Noticia getNoticia() {
        return this.noticia;
    }
    
    public void setNoticia(Noticia noticia) {
        this.noticia = noticia;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }




}


